### PR TITLE
Adding Corretto-21 images, update github actions

### PR DESCRIPTION
**Pull request by mrserb**
Description of changes:

Adding Corretto-21 images using the similar approach we did for 17 and 20. The difference from 20 is that we do not have al2023-generic.

### CODE REVIEW

**Review by lutkerd — COMMENTED** [review]
We won't have AL2 with the platform RPMs just the generic

**Comment by lutkerd** [comment]
I don't see changes to bin/apply-template.py or versions.json, were those missed?

**Comment by benty-amzn** [comment]
> I don't see changes to bin/apply-template.py or versions.json, were those missed?

versions.json is there but +1 for the missing script changes

**Comment by mrserb** [comment]
The work still in progress, the PR is in draft.

**Comment by mrserb** [comment]
Do I need to update tags manually as well?

**Comment by lutkerd** [comment]
> Do I need to update tags manually as well?

Run the script locally to make sure it worked, the is an GHA to run it after you merge and add the comment on your commit.

**Comment by mrserb** [comment]
bash bin/update-dockerfiles.sh
and
python3 bin/tag-generator.py | tee .tags
do not produce any errors

**Comment by lutkerd** [comment]
missing test/test-image-corretto21-jre.yaml to fix the last 2 failures.

**Comment by mrserb** [comment]
all checks are passed

**Review by lutkerd — APPROVED** [review]

**Comment by CasaSky** [comment]
can i access to the docker image of corretto 21?
**docker pull amazoncorretto:21**
fails with 
**Error response from daemon: manifest for amazoncorretto:21 not found: manifest unknown: manifest unknown**

**Comment by SentryMan** [comment]
> can i access to the docker image of corretto 21? **docker pull amazoncorretto:21** fails with **Error response from daemon: manifest for amazoncorretto:21 not found: manifest unknown: manifest unknown**

I'm also getting this

**Comment by fbellomi** [comment]
> > can i access to the docker image of corretto 21? **docker pull amazoncorretto:21** fails with **Error response from daemon: manifest for amazoncorretto:21 not found: manifest unknown: manifest unknown**
> 
> I'm also getting this

+1

**Comment by benty-amzn** [comment]
The corretto 21 images have not been published to [official-images/amazoncorretto](https://github.com/docker-library/official-images/blob/master/library/amazoncorretto) yet. We expect them to be available soon and we'll post an update here when they're ready.

**Comment by benty-amzn** [comment]
[official-images#15408](https://github.com/docker-library/official-images/pull/15408) is the PR for the update. Once that's merged images should be available on dockerhub and ecr gallery within a few hours.

**Pull request merged**
