### PR TITLE
Add dockerfiles for alpine 3.15

### PR DESCRIPTION
**Pull request by cliveverghese**
*Issue #, if available:*

Add Dockerfiles for alpine3.15. 

Addresses #76

### CODE REVIEW

**Review by lutkerd — APPROVED** [review]

**Comment by JohnPreston** [comment]
Can I enquire why you guys are using dockerhub capabilities over what you could do by using CodeBuild / GH Actions ?
Clearly public ECR is gaining in popularity and I am not sure why you guys would not showcase the AWS Services capabilities at the same time? (From previous PR convo anyway).

**Comment by cliveverghese** [comment]
> Can I enquire why you guys are using dockerhub capabilities over what you could do by using CodeBuild / GH Actions ?

We still receive a significant number of pulls from Dockerhub for amazoncorretto image as the easiest command `docker pull amazoncorretto` retrieves the images from this location. 

> Clearly public ECR is gaining in popularity and I am not sure why you guys would not showcase the AWS Services capabilities at the same time? (From previous PR convo anyway).

The images will be available it ECR as well at [amazoncorretto](https://gallery.ecr.aws/amazoncorretto/amazoncorretto) and [docker](https://gallery.ecr.aws/docker/library/amazoncorretto)

**Comment by JohnPreston** [comment]
> We still receive a significant number of pulls from Dockerhub for amazoncorretto image as the easiest command `docker pull amazoncorretto` retrieves the images from this location.

I suppose my point is, you could still push to dockerhub without buidling on dockerhub.

This would allow for a much nicer way IMHO than rely on dockerhub. Alpine is version 3.15, grows quickly. Are you going to have a subfolder for every single alpine version just because dockerhub does not support an `ARG` to override the version? /shrug

**Comment by lutkerd** [comment]
When Alpine updates 3.15, they will have tags for both 3.15.1 and 3.15 to point to the same image. At least that is what they have done for the previous releases. Dockerhub will automatically rebuild our alpine based images for us without us needing to build and maintain infrastructure to query all of the base images, run workflows and push new images. 

As an "Official Image" I don't think we have the ability to push a new image and it must be built by Dockerhub from the commit in https://github.com/docker-library/official-images/blob/master/library/amazoncorretto

**Pull request merged**
